version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./django_project:/app
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:

