version: "3"
services:
  web:
    image: nfor/auto_deploy
    expose:
      - "80"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30